version: "3.9"
services:
  songmate-db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: kuba
      POSTGRES_USER: kuba
      POSTGRES_DB: kuba